### ISSUE TITLE
Gas sensor values

### ISSUE THREAD

**Issue by kylix34** [DFRobot/DFRobot_BME680#5]
Hello,

I'm getting pretty high values from the gas sensor: somewhere between 90-980 ppm in the living room.
Is it normal?

Bosch datasheet talks about the IAQ Index Air Quality between 50-500:

0 – 50 good
51 – 100 average
101 – 150 little bad
151 – 200 bad
201 – 300 worse
301 – 500 very bad

At 980ppm I suppose I should be dead :D

**Comment by MariusRumpf** [comment]
I am getting the same results indoor here with some, for me unreasonable jumps over time.

![Screenshot](https://user-images.githubusercontent.com/2364426/31731063-27da0d10-b434-11e7-8c85-ab53b40d89b1.png)

**Comment by janzieg** [comment]
Same for me here (using https://github.com/watterott/BME680-Breakout) - i know about other voc sensors (iaq core, ccs811) that it might take some time (about 2 days) until automatic calibration (baseline correction) is on a good level which results in "realistic" values. Maybe the BME680 needs some more time (and changing air conditions - open your Windows at least once a day) until calibrated...?

**Comment by MariusRumpf** [comment]
@janzieg The graph from above is from a sensor running for about 3 weeks in the same place. It has only been restarted for a software update with a new version of the library a week ago. I have been using the same breakout as you mentioned. I have seen this drops since the beginning with old and new versions of the library.

**Comment by janzieg** [comment]
@MariusRumpf  Have you tried other drivers libs yet ? The sensor is not really usable like this.
As far as I could see, the original bosch library was integrated in this lib, so it supposed to be correct (even not guaranteed). Maybe the board is not designed correctly ?

**Comment by MariusRumpf** [comment]
@janzieg I have not tried other libraries and only used I2C. Maybe it's the board... I don't know. 

Feel free to ask if more details are needed.

**Comment by kylix34** [comment]
This is my graph for one week (I have the sensor running for more than 2 weeks now):
![bme680](https://user-images.githubusercontent.com/13137515/31743484-9f769db2-b45b-11e7-97d2-cda1fe22bc78.jpg)

**Comment by WeMakeIt1995** [comment]
@kylix34 , @MariusRumpf 
Thanks for yours feedback.
That gas result is not normal, so we delete it and please use gas resistance to statistics air quality.
I am sorry for the inconvenience caused.

**Comment by BlueDot-Arduino** [comment]
Please note that the gas resistance is not the same as the IAQ index. 
The BSEC algorithm from Bosch uses the measured gas resistance to calculate the IAQ index.
The problem is that the BSEC algorithm is not so easy to read. 
While the sensor API can be downloaded from Github or from the website from Bosch Sensortec (all those .c and .h files), the BSEC files consist of .a and .lib files.
So far I didn't manage to open them, but the formulas to calculate the IAQ index are written there.

**Comment by janzieg** [comment]
@BlueDot-Arduino Thanks for your efforts! So the BSEC library (with closed source) cannot be included "as it is" - as precompiled binary (there seem to exist one for ARM_CORTEX, ESP8266, RL78) ?

**Comment by BlueDot-Arduino** [comment]
I'm not sure, I haven't tried that yet. But apparently, the BSEC library "as it is", is only compatible with 32 bit MCU platforms (according to [Bosch](https://www.bosch-sensortec.com/bst/products/all_products/bsec)).

That would mean, we could use the BSEC library from Bosch, but only with 32-bit microcontrollers, like the Arduino Due, and not with the Uno. But I'm speculating.

**Comment by wklenk** [comment]
I am currently trying to get this BSEC library working with a STM32F103C board ("Blue Pill") which has an ARM Cortex M3. I already managed that the linker in the Arduino IDE is no longer complaining about missing functions and symbols, but when I flash the software to the board just nothing happens. Any hint is appreciated :)

**Comment by sebswed** [comment]
I have an Arduino Due and the BME680 on I2C. I'm not that skilled but I'm more than willing to test any code if that is of any help.

**Comment by AlesSt** [comment]
Hi all!
Made an acc here just to answer here on this topic :)
Have been testing the watterott BME680 sensor for 2-3 weeks now and today I got VOC working (thankgod i havent upgraded library to the last one :)
VOC works with previous version of library IF you follow this - make measurements every second.
I incorporated it at the end of each loop with delay 1000 (MUST be at least 1000 = 1s) and after a minute or so it works (meaning measurements are not jumping all over the place) as it should.
I guess this is because the plate in sensor must be warm the whole time for the algorithm to calculate resistance correctly.........
@forKnowYou.......perhaps you should heat the plate longer? or once longer and next one as it is now and then return the result to the command
if there are some commands I could use in my sketch before the measurement (to heat the plate for 100ms, for 200ms...., to find out the time it needs to be heated) i can test and find the right procedure so u can implement bme.readGas() again?

And forgot to mention....burn-in!!!! u must do it for the sensor.....5 minutes when new


EDIT:  after a day or two measuremnts went off the charts again.....so not good for long term deployment :(

**Comment by ouki-wang** [comment]
I have got correct IAQ using FireBeetle-ESP8266.  
You have to wait 300 seconds for the bmp680 to heat up.
![iaq](https://user-images.githubusercontent.com/13196063/32814478-6a1abe60-c9ea-11e7-8816-b236f0be6db8.png)

I have uploaded the iaq source code to the respository, upload static library files to the FireBeetle-ESP8266 SDK, updated SDK to 2.3.1, to complete the test.

**Comment by sebswed** [comment]
There is an interesting topic on this on https://forum.fhem.de/index.php/topic,78619.60.html that I have been following with google translate that may be of help.
